/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{html,js,jsx}',
    './components/**/*.{html,js,jsx}',
    './sections/**/*.{html,js,jsx}',
    './styles/**/*.{js,jsx}',
  ],
  mode: 'jit',
  theme: {
    extend: {
      colors: {
        'primary-black': '#F8BBD0',
        'secondary-white': '#A9A9A9',
        'light-lavender': '#E3A6FF',
        'medium-lavender': '#D6C8E5',
        'dark-lavender': '#A77BCA',
        'light-purple': '#D1B3E0',
        'medium-purple': '#A25EB8',
        'dark-purple': '#5D3B88',
        'deep-purple': '#4B0072',
        'soft-purple': '#B59CC0',
        'rich-purple': '#6F2C91',
        'light-pink': '#FFB3D1',
        'medium-pink': '#FF6F91',
        'dark-pink': '#D5006D',
        'coral-pink': '#FF6F61',
        'light-coral': '#FF9A8B',
        'dark-coral': '#C54D39',
        'pink-red': '#FF3B5D',
        'light-pink-red': '#FF6F91',
        'dark-pink-red': '#C72C4B',
        'pink-purple': '#DA4F95',
        'light-pink-purple': '#EA6DAB',
        'dark-pink-purple': '#A1356E',
        'soft-pink': '#000000',
        'medium-brown': '#7b3d3d',
        'deep-blue': '#001F3F',
        'medium-blue': '#007BFF',
        'light-blue': '#ADD8E6',
        'sky-blue': '#87CEEB',
        'teal-blue': '#008080',
        'navy-blue': '#001F3F',
        'soft-blue': '#A3C1DA',
        'steel-blue': '#4682B4',
        'dark-blue': '#003366',
        'powder-blue': '#B0E0E6',
        'deep-red': '#8B0000',
        'medium-red': '#FF0000',
        'light-red': '#FF7F7F',
        'crimson-red': '#DC143C',
        'fire-engine-red': '#CE2029',
        'rose-red': '#C72C4B',
        'coral-red': '#FF4C4C',
        'dark-red': '#660000',
        'scarlet-red': '#FF2400',
        'soft-red': '#FFB6C1',
        'jet-black': '#343434',
        'charcoal-black': '#444444',
        'soft-black': '#696969',
        'onyx-black': '#353839',
        'deep-black': '#000000',
        'rich-black': '#1C1C1C',
        'matte-black': '#1A1A1A',
        'black-pearl': '#101820',
        'ink-black': '#2B2B2B',
        'graphite-black': '#3D3D3D',
        'berry-maroon': '#992539',
        'blush-maroon': '#B84E5E;',
        'dusty-rose': '#D8BFD8',
        'terra-cotta-pink': '#D57D6B',
        'muted-raspberry': '#A95B7D',
        'rosewood-brown': '#65000B',
        'mauve-taupe': '#A76E8A',
        'burnt-sienna': '#9F4F3B',
        'chestnut-rose': '#CD5C5C',
        'rusty-pink': '#C25B61',
        'antique-pink': '#D1908C',
        'faded-brick': '#C65D4D',

      },
      transitionTimingFunction: {
        'out-flex': 'cubic-bezier(0.05, 0.6, 0.4, 0.9)',
      },
    },
  },
  plugins: [],
};
